### ISSUE TITLE
Missing dshowcapture.hpp file ?

### ISSUE THREAD

**Issue by xiaohuahegege** [charlescao460/NetLibDirectshowCapture#1]
I compiled the NetLibDirectshowCapture solution and it shows that dshowcapture.hpp is missing, what's the matter?

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'dshowcapture.hpp': No such file or directory	NetLibDirectshowCapture	F:\NetLibDirectshowCapture-main\NetLibDirectshowCapture\pch.h	14

**Comment by charlescao460** [comment]
Hi, Sorry about the late reply, but could you please try `git clone --recurse-submodules `?

Hope you've solved the problem.
